# Generated by Django 4.2.6 on 2024-03-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_name',
            field=models.CharField(default='Entry Name', max_length=50),
        ),
    ]
