# Generated by Django 4.2.6 on 2024-03-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_entry_entry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='mood',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_name',
            field=models.CharField(default='New Entry', max_length=50),
        ),
    ]
