# Generated by Django 4.2.6 on 2024-03-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_entry_mood_alter_entry_entry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recently_accessed_journals',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
