# Generated by Django 4.2.6 on 2024-03-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_user_recently_accessed_journals'),
        ('journals', '0005_achievement_level'),
    ]

    operations = [
    ]
