# Generated by Django 4.2.6 on 2024-03-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_merge_20240325_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
