# Generated by Django 4.2.6 on 2024-03-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_alter_achievement_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='multimedia_file',
            field=models.FileField(blank=True, null=True, upload_to='multimedia/'),
        ),
    ]
