# Generated by Django 4.2.6 on 2024-03-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0008_entry_multimedia_file'),
        ('journals', '0008_journal_date'),
    ]

    operations = [
    ]
